
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 23 21:28:17 IST 2015
//----------------------------------------------------

package IC.Parser;

/** CUP generated interface containing symbol constants. */
public interface LibrarySym {
  /* terminals */
  public static final int INT_KEYWORD = 3;
  public static final int SEMICOLON = 17;
  public static final int LP = 10;
  public static final int RP = 11;
  public static final int CLASS_KEYWORD = 7;
  public static final int STATIC_KEYWORD = 9;
  public static final int ID = 6;
  public static final int LC = 14;
  public static final int LB = 12;
  public static final int RC = 15;
  public static final int RB = 13;
  public static final int COMMA = 16;
  public static final int EOF = 0;
  public static final int STRING_KEYWORD = 5;
  public static final int error = 1;
  public static final int VOID_KEYWORD = 2;
  public static final int BOOLEAN_KEYWORD = 4;
  public static final int CLASS_ID = 8;
}

