
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 23 21:28:17 IST 2015
//----------------------------------------------------

package slp;

/** CUP generated interface containing symbol constants. */
public interface SlpSymIgnore {
  /* terminals */
  public static final int DIVIDE = 38;
  public static final int FALSE_LITERAL = 23;
  public static final int STRING_LITERAL = 25;
  public static final int MULT = 37;
  public static final int UMINUS = 49;
  public static final int REMINDER = 39;
  public static final int EQUALS_OP = 44;
  public static final int BOOLEAN_KEYWORD = 11;
  public static final int THIS_KEYWORD = 19;
  public static final int MINUS = 36;
  public static final int TRUE_LITERAL = 22;
  public static final int SEMICOLON = 4;
  public static final int LP = 27;
  public static final int COMMA = 5;
  public static final int RP = 28;
  public static final int OR_OP = 47;
  public static final int PLUS = 35;
  public static final int NEW_KEYWORD = 20;
  public static final int ASSIGN = 48;
  public static final int NULL_LITERAL = 24;
  public static final int LARGER_OP = 41;
  public static final int DOT = 33;
  public static final int ID = 2;
  public static final int AND_OP = 46;
  public static final int EOF = 0;
  public static final int LC = 29;
  public static final int LB = 31;
  public static final int error = 1;
  public static final int RC = 30;
  public static final int RB = 32;
  public static final int SMALLER_EQ_OP = 42;
  public static final int SMALLER_OP = 40;
  public static final int NOT_EQUALS_OP = 45;
  public static final int RETURN_KEYWORD = 13;
  public static final int CLASS_ID = 3;
  public static final int STATIC_KEYWORD = 8;
  public static final int WHILE_KEYWORD = 16;
  public static final int INT_KEYWORD = 10;
  public static final int CLASS_KEYWORD = 6;
  public static final int STRING_KEYWORD = 12;
  public static final int CONTINUE_KEYWORD = 18;
  public static final int LENGTH_KEYWORD = 21;
  public static final int EXCLAMATION_MARK = 34;
  public static final int VOID_KEYWORD = 9;
  public static final int IF_KEYWORD = 14;
  public static final int ELSE_KEYWORD = 15;
  public static final int EXTENDS_KEYWORD = 7;
  public static final int LARGER_EQ_OP = 43;
  public static final int INTEGER_LITERAL = 26;
  public static final int BREAK_KEYWORD = 17;
}

