
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 21 19:08:08 IST 2015
//----------------------------------------------------

package slp;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 36;
  public static final int LCBR = 11;
  public static final int LTE = 40;
  public static final int UMINUS = 49;
  public static final int STRING_RESERVED = 10;
  public static final int INTEGER = 18;
  public static final int LPAREN = 13;
  public static final int CONTINUE = 26;
  public static final int INT = 8;
  public static final int MINUS = 34;
  public static final int STATIC = 6;
  public static final int RPAREN = 14;
  public static final int SEMICOLON = 4;
  public static final int LT = 41;
  public static final int COMMA = 17;
  public static final int CLASS = 5;
  public static final int MULTIPLY = 35;
  public static final int PLUS = 33;
  public static final int ASSIGN = 48;
  public static final int IF = 22;
  public static final int THIS = 27;
  public static final int DOT = 47;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int LAND = 38;
  public static final int RCBR = 12;
  public static final int LB = 15;
  public static final int RETURN = 21;
  public static final int EQUAL = 44;
  public static final int TRUE = 30;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int RB = 16;
  public static final int LOR = 39;
  public static final int NULL = 32;
  public static final int MOD = 37;
  public static final int BREAK = 25;
  public static final int VOID = 7;
  public static final int GTE = 42;
  public static final int ELSE = 23;
  public static final int WHILE = 24;
  public static final int NEQUAL = 45;
  public static final int CLASS_ID = 2;
  public static final int EXTENDS = 20;
  public static final int STRING = 19;
  public static final int LNEG = 46;
  public static final int FALSE = 31;
  public static final int GT = 43;
  public static final int PRINT = 50;
  public static final int LENGTH = 29;
}

