package slp;

public class terminalNames {
	public static final String[] terminalNames = new String[] { "EOF", "error", "ID", "CLASS_ID", "SEMICOLON", "COMMA",
			"CLASS_KEYWORD", "EXTENDS_KEYWORD", "STATIC_KEYWORD", "VOID_KEYWORD", "INT_KEYWORD", "BOOLEAN_KEYWORD",
			"STRING_KEYWORD", "RETURN_KEYWORD", "IF_KEYWORD", "ELSE_KEYWORD", "WHILE_KEYWORD", "BREAK_KEYWORD",
			"CONTINUE_KEYWORD", "THIS_KEYWORD", "NEW_KEYWORD", "LENGTH_KEYWORD", "TRUE_LITERAL", "FALSE_LITERAL",
			"NULL_LITERAL", "STRING_LITERAL", "INTEGER_LITERAL", "LP", "RP", "LC", "RC", "LB", "RB", "DOT",
			"EXCLAMATION_MARK", "PLUS", "MINUS", "MULT", "DIVIDE", "REMINDER", "SMALLER_OP", "LARGER_OP",
			"SMALLER_EQ_OP", "LARGER_EQ_OP", "EQUALS_OP", "NOT_EQUALS_OP", "AND_OP", "OR_OP", "ASSIGN", "UMINUS" };
}
