
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 23 21:28:16 IST 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface LibrarySym {
  /* terminals */
  public static final int TIMES = 14;
  public static final int MOD = 16;
  public static final int INT_KEYWORD = 3;
  public static final int SEMICOLON = 25;
  public static final int PLUS = 12;
  public static final int LP = 18;
  public static final int SEMI = 11;
  public static final int RP = 19;
  public static final int CLASS_KEYWORD = 7;
  public static final int STATIC_KEYWORD = 10;
  public static final int ID = 6;
  public static final int LC = 22;
  public static final int LB = 20;
  public static final int RC = 23;
  public static final int RB = 21;
  public static final int COMMA = 24;
  public static final int EXTENDS_KEYWORD = 9;
  public static final int NUMBER = 26;
  public static final int EOF = 0;
  public static final int DIVIDE = 15;
  public static final int STRING_KEYWORD = 5;
  public static final int MINUS = 13;
  public static final int error = 1;
  public static final int VOID_KEYWORD = 2;
  public static final int BOOLEAN_KEYWORD = 4;
  public static final int CLASS_ID = 8;
  public static final int UMINUS = 17;
}

